spring:
  application:
    name: canvasnotifier
  session:
    store-type: none
  config.import: optional:${app.fullFilePath}/${app.overridesFileName}, optional:${app.fullFilePath}/security.properties, classpath:canvas.properties, optional:classpath:git.properties, optional:classpath:email.properties, classpath:lti-registrations.properties, optional:classpath:denodo.properties,optional:classpath:derdack.properties,
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp:
          use_jdbc_metadata_defaults: false
      jadira:
        usertype:
          autoRegisterUserTypes: true
  datasource:
    url: ${lms.db.url}
    username: ${lms.db.user}
    password: ${lms.db.password}
    type: ${lms.db.poolType}
    denodo:
      driverClassName: ${denodo.db.driverClass}
      jdbcUrl: ${denodo.db.url}
      username: ${denodo.db.user}
      password: ${denodo.db.password}
  cloud.vault.enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${oauth.tokenprovider.url}/.well-known/jwks.json
  rabbitmq:
    addresses: ${lms.rabbitmq.address.${app.env}}
    username: ${lms.rabbitmq.username.${app.env}}
    password: ${lms.rabbitmq.password.${app.env}}
    virtualHost: ${lms.rabbitmq.virtualHost.${app.env}}
    listener.simple:
      acknowledge-mode: manual
      missing-queues-fatal: false
      retry:
        enabled: true
        initial-interval: 3s
        max-attempts: 3
        max-interval: 10s
        multiplier: 2
canvasnotifier:
  version: @app.version@
  env: ${app.env}
  batchNotificationEmail: iu-uits-es-ess-lms-notify@exchange.iu.edu,lms-func-l@iu.edu
  canvasNotifierQueueName: notifier_${lms.rabbitmq.queue_env_suffix}
server:
  error:
    whitelabel:
      enabled: false
  servlet:
    session:
      timeout: 30m

app:
  env: dev
  fullFilePath: file:/usr/src/app/config
  overridesFileName: overrides.properties

management:
  endpoint.lms.enabled: true
  endpoints.web.exposure.include: health,lms
  health.redis.enabled: false
  info.java.enabled: true

---

spring:
  config.activate.on-profile: redis-session
  session:
    store-type: redis
    redis.namespace: canvasnotifier-${app.version}:session
management.health.redis.enabled: true

---

spring:
  config:
    activate.on-profile: vault
    import: vault://
  cloud.vault:
    enabled: true
    config:
      lifecycle.lease-endpoints: sysleases
    generic:
      enabled: false
    kv:
      enabled: true
      backend: ua-vpit/enterprise-systems/lms/kv
      application-name: canvasnotifier

---

spring:
  config:
    activate.on-profile: swagger
springdoc:
  api-docs:
    enabled: true
    path: /api/v3/api-docs
  cache.disabled: true
  packagesToScan: edu.iu.uits.lms.canvasnotifier.rest
  swagger-ui:
    enabled: false
    disable-swagger-default-url: true
    path: /api/swagger-ui.html
    # Setting supportedSubmitMethods to an empty list is what turns off the "try it out" button
    #    supportedSubmitMethods:
    oauth:
      clientId: ${oauth.tokenprovider.clientId}
  oAuthFlow:
    authorizationUrl: ${oauth.tokenprovider.url}/oauth/authorize
    tokenUrl: ${oauth.tokenprovider.accessTokenUri}